#!/bin/bash

cd `dirname $0`
source ./get_version_number
version_format_is_ok "1.5-1-g9097c0e"
exit 0

cmd="./increase_version_number --production --yes"
echo "------------------------------------ $cmd ----------------------------------------"
eval $cmd

cmd="./increase_version_number --production --yes"
echo "------------------------------------ $cmd ----------------------------------------"
eval $cmd

cmd="./increase_version_number --development --yes"
echo "------------------------------------ $cmd ----------------------------------------"
eval $cmd

cmd="./increase_version_number --production --major --yes"
echo "------------------------------------ $cmd ----------------------------------------"
eval $cmd

cmd="./increase_version_number --development --major --yes"
echo "------------------------------------ $cmd ----------------------------------------"
eval $cmd

cmd="./increase_version_number --development --majorRRR --yes"
echo "------------------------------------ $cmd ----------------------------------------"
eval $cmd

